config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end
  root "homes#show"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end
  resource :search, only: [:show]
  resources :text_shouts, only: [:create, :destroy]
  resources :photo_shouts, only: [:create, :destroy]
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

  validates :follower_id, uniqueness: { scope: :followed_user_id }
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :image
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  has_one :shout, as: :content, dependent: :destroy
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true
  validates :content, presence: true, length: { maximum: 160 }
  default_scope { order(created_at: :desc) }

  def self.search(search)
    text_shouts = TextShout.where("content ILIKE ?", "%#{search}%").select(:id)
    Shout.where(content_type: "TextShout", content_id: text_shouts).includes(:content, :user)
  end
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
  has_one :shout, as: :content, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :followed_user_relationships,
           class_name: "FollowingRelationship",
           foreign_key: :follower_id

  has_many :followed_users, through: :followed_user_relationships

  has_many :following_user_relationships,
           class_name: "FollowingRelationship",
           foreign_key: :followed_user_id

  has_many :followers, through: :following_user_relationships

  def dashboard_shouts
    timeline.includes(:content, :user)
  end

  def following?(user)
    followed_users.include?(user)
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.delete(user)
  end

  def to_param
    username
  end

  private

  def timeline
    Shout.where(user_id: timeline_user_ids).order(created_at: :desc)
  end

  def timeline_user_ids
    [id] + followed_user_ids
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers

  before_action :require_login
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
    @shouts = current_user.dashboard_shouts
    @followers = current_user.followers
    @followed_users = current_user.followed_users
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    user = find_user
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = find_user
    current_user.unfollow(user)
    redirect_to user
  end

  private

  def find_user
    User.find_by(username: params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login
  def show
    @user = User.new
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController
  def create
    photo_shout = PhotoShout.new(photo_shout_params)
    shout = current_user.shouts.new(content: photo_shout)
    if shout.save
      redirect_to dashboard_path
    else
      render "dashboard/show"
    end
  end

  def destroy
    photo_shout = PhotoShout.find(params[:id])
    photo_shout.image.destroy
    photo_shout.shout.delete
    photo_shout.delete
    redirect_to dashboard_path
  end

  private

  def photo_shout_params
    params.require(:photo_shout).permit(:image)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @search = Shout.search(params[:search])
    if params[:utf8]
      redirect_to "/search?=#{params[:search]}"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def create
    shout = current_user.shouts.new(shout_params)
    if shout.save
      redirect_to dashboard_path
    else
      render "dashboard/show"
    end
  end

  private

  def shout_params
    params.require(:shout).permit(:body)
  end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
  def create
    @text_shout = TextShout.new(text_shout_params)
    shout = current_user.shouts.new(content: @text_shout)
    if shout.save
      respond_to do |format|
        format.html { redirect_to dashboard_path }
        format.js {}
        format.json { render json: @text_shout.to_json }
      end
    else
      render "dashboard/show"
    end
  end

  def destroy
    text_shout = TextShout.find(params[:id])
    text_shout.shout.delete
    text_shout.delete
    redirect_to dashboard_path
  end

  private

  def text_shout_params
    params.require(:text_shout).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_errors.html.erb
<% if object.errors.any? %>
  <p>Could not save:</p>
  <% object.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
<% end %>

app/views/application/_search.html.erb
<%= form_tag :search, method: :get do %>
  <%= text_field_tag :search %>
  <%= submit_tag "Search", name: nil %>
<% end %>

app/views/application/_sign_in_form.html.erb
<%= form_for :session, url: session_path do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign in" %>
  </div>
<% end %>

app/views/application/_sign_up_form.html.erb
<%= form_for user do |form| %>
  <%= render "errors", object: user %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<div class="sidebar">
<div class="super">
  <h3 class="black box">@<%= current_user.username %></h3>
</div>

<div class="super">
  <div class="blue box">
    <h4 class="black">Shouts!!</h4>
    <h4><%= current_user.shouts.size  %></h4>
  </div>
</div>

<%= render "text_shouts/form", shout: @text_shout %>
<%= render "photo_shouts/form", shout: @photo_shout %>
</div>

<div class="middle">
    <%= render @shouts %>
</div>

<div class="right-side">
  <h4 class="following">
    Following: <%= render @followed_users %>
  </h4>
  <h4 class="followers">
    Followers: <%= render @followers %>
  </h4>
</div>

app/views/homes/show.html.erb
<h1>Welcome to Shoutr</h1>
<div class="new_form">
  <%= render "sign_in_form" %>
</div>
<div class="new_form">
  <%= render "sign_up_form", user: @user %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar">
<% if signed_in? %>
  Welcome <%= current_user.username %>
  <span class="sign_out"><%= link_to "Sign out", session_path, method: :delete %></span>
  <div>
    <%= render "search" %>
  </div>
<% end %>
</nav>

<%= yield %>

</body>
</html>

app/views/photo_shouts/_form.html.erb
<div>
<%= form_for shout, html: { class: "new_shout" } do |form| %>
  <%= render "errors", object: shout %>
  <div>
    <%= form.file_field :image, class: "shout_body" %>
  </div>
  <%= button_tag(class: "shout_button") do %>
    <%= icon("bullhorn") %>
  <% end %>
<% end %>
</div>

app/views/photo_shouts/_photo_shout.html.erb
<%= image_tag photo_shout.image, width: 200 %>

app/views/searches/show.html.erb
<div class="middle">
<% @search.each do |text_shout| %>
  <%= render "shouts/shout", shout: text_shout %>
<% end %>
</div>

app/views/shouts/_shout.html.erb
<div id="shoutr">
<%= div_for shout do %>
  <div class="super shout-border">
  <div class="shout blue box">
    <%= link_to "@#{shout.user.username}", shout.user %> <span class="black">·</span> <%= time_ago_in_words(shout.created_at) %> ago<br>

    <span class="black"><%= render shout.content %></span>

    <% if shout.user == current_user %>
      <%= link_to "Delete", shout.content, method: :delete  %>
    <% end %>
  </div>
</div>
<% end %>
</div>

app/views/text_shouts/_form.html.erb
<div>
<%= form_for shout, html: { class: "new_shout" }, remote: true do |form| %>
  <%= render "errors", object: shout %>
  <div>
    <%= form.text_field :content, class: "shout_body", size: 30 %>
  </div>
  <%= button_tag(class: "shout_button") do %>
    <%= icon("bullhorn") %>
  <% end %>
<% end %>
</div>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.content %>

app/views/users/_user.html.erb
<%= link_to user.username, user %>

app/views/users/new.html.erb
<%= render form, user: @user %>

app/views/users/show.html.erb
<div class="sidebar">
  <div class="userinfo" >
    <h3 class="black box">@<%= @user.username %></h3>
    <div class="box">

      <% if current_user != @user %>
        <% if current_user.following?(@user) %>
          <%= button_to(unfollow_user_path(@user), class: "button unfollow", method: :delete) do %>
            Unfollow
          <% end %>
        <% else %>
          <%= button_to(follow_user_path(@user), class: "button follow") do  %>
            Follow
          <% end %>
        <% end %>
      <% end %>

        Following: <%= render @user.followed_users %>
    </div>
</div>
</div>

<div class="middle">
  <%= render @shouts %>
</div>